#!/usr/local/bin/python3
import itertools
import collections
import re
import networkx
import pygraphviz
from networkx.drawing.nx_agraph import write_dot
import string
import sys
import unittest

def input_stream():
    if len(sys.argv) > 1:
        if sys.argv[1] == '-':
            return sys.stdin
        else:
            return open(sys.argv[1])
    else:
        return open('input.txt')

states = list(range(10))

def validate_password(password):
    for letter in string.ascii_lowercase[:-3]:
        if letter + letter[1] + letter[2] in password:
            break
    else:
        return False
    if any(l in password for l in 'iol'):
        return False
    overlaps = 0
    for letter in string.ascii_lowercase:
        if letter + letter in password:
            overlaps += 1
    return overlaps >= 2

def next_password(password):
    return ''.join(string.ascii_lowercase[i] for i in next_indices(password))

def next_indices(password):
    carry = 0
    indices = []
    rev = ''.join(reversed(password))
    num = len(string.ascii_lowercase)
    for i, c in enumerate(password):
        step = i + 1 + carry
        if step >= num:
            indices.append(step % num)
            carry = 1
        else:
            indices.append(step)
            carry = 0
    return num


def process_line(state, line, handle, state_transition=lambda x, line: x):
    original = line
    part = None
    if state == 0:
        part = line
    elif state == 1:
        pass
    elif state == 2:
        pass
    elif state == 3:
        pass
    handle(part)
    return state_transition(state, original)

def solution(line):
    return line

def main():
    state = 0
    units = []
    mapping = {}
    g = networkx.DiGraph()
    with input_stream() as f:
        for line in f:
            line = line.strip()
            state = process_line(state, line, parts.append)
    count = 0
    product = 1
    for part in parts:
        pass

    answer = None
    if units:
        answer = sum(solution(u) for u in unites)
    elif mapping:
        answer = solution(mapping)
    elif g:
        answer = solution(g)
    else:
        raise Exception()

    if os.environ.get('DEBUG'):
        print(state)
        for unit in units:
            print units
        for k, v in mapping.items():
            print(k, v)
        if g.nodes():
            write_dot(g, sys.stdout)

    return answer

class Tests(unittest.TestCase):

    def test_self(self):
        self.assertEquals(next_password('abcdefgh'), 'abcdffaa')

if __name__ == '__main__':
    print(main())
